import type { Metadata } from "next";
// import '../globals.css';
// import { ThemeProvider } from "@mui/material/styles";
// import theme from "@/theme";
// import Header from "@/components/header";
// import { Box } from "@mui/material";
// import ResponsiveDrawer from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Products | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Layout UI */}
        <main>{children}</main>
      </body>
    </html>
  );
}
