import type { Metadata } from 'next';
import '../globals.css';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/theme';
import Header from '@/components/header';
import { Box } from '@mui/material';
import ResponsiveDrawer from '@/components/sidebar';

export const metadata: Metadata = {
  title: 'Products | Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <Box display='flex'>
        <ResponsiveDrawer />
        <Box
          component='main'
          flexGrow={1}
          sx={{
            maxHeight: '100vh',
            overflow: 'auto',
            backgroundColor: '#EEF2F6',
          }}
        >
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </Box>
      </Box>
    </>
  );
}
